//User
export const LOGIN = 'LOGIN';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const NOT_RECEIVE_USER = 'NOT_RECEIVE_USER';
export const LOGOUT = 'LOGOUT';
export const CLEAR_USER = "CLEAR_USER"
export const NOT_CLEAR_USER = "NOT_CLEAR_USER"

//Network
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const NETWORK_ACCESS_DENIED = 'NETWORK_ACCESS_DENIED';
export const NETWORK_CONFLICT = 'NETWORK_CONFLICT';
export const NETWORK_SERVER_ERROR = 'NETWORK_SERVER_ERROR';
export const NETWORK_UNAUTHORIZED = 'NETWORK_UNAUTHORIZED';
export const NETWORK_DEFAULT_ERROR = 'NETWORK_DEFAULT_ERROR';
export const RESET_NETWORK_ERROR = 'RESET_NETWORK_ERROR';
export const RESET_NETWORK_ERRORS = 'RESET_NETWORK_ERRORS';
export const NETWORK_BAD_REQUEST = 'NETWORK_BAD_REQUEST';